version: '3.8'

services:
  python-app:
    build: ./python
    ports:
      - "5000:5000"
    container_name: hello-world-python

  java-app:
    build: ./java
    ports:
      - "5001:5001"
    container_name: hello-world-java
